var availableTags=[
"<abstract>","<abstract concept>","<abstract social>",
"<activity>","<activity game>","<activity sport>","<activity video>",
"<adj>","<adj appearance>","<adj emotion>","<adj nationality>","<adj weather>",
"<adv>","<adv emotion>","<adv sexy>",
"<color>","<color primary>","<color secondary>",
"<conj>",
"<country>","<country africa>","<country middleeast>","<country asia>","<country oceania>","<country centralamerica>","<country europe>","<country eurasia>","<country southamerica>",
"<emo>",
"<em>",
"<x>",
"<face>",
"<firstname>","<firstname female>","<firstname male>","<firstname male?>","<firstname female?>",
"<greet>",
"<surname>",
"<noun>","<noun animal>","<noun dog>","<noun insect>","<noun article>","<noun clothes>","<noun ball>","<noun round>","<noun food>","<noun body>","<noun long>","<noun hole>","<noun container>","<noun weapon>","<noun drug>","<noun fruit>","<noun furniture>","<noun surface>","<noun job>","<noun liquid>","<noun tool>","<noun person>","<noun plant>","<noun shape>","<noun vehicle>",
"<sound>",
"<title>",
"<place>","<place indoor>","<place building>","<place natural>","<place outdoor>",
"<prefix>","<prefix position>","<prefix quantity>",
"<prepos>","<prepos space>","<prepos time>",
"<pron>","<pron female>","<pron male>","<pron neutral>",
"<quality>","<quality human>","<quality physical>",
"<rel>","<rel female>","<rel male>","<rel neutral>",
"<sconj>",
"<substance>","<substance liquid>",
"<timeadv>","<timeadv frequency>","<timeadv time>","<timeadv past>","<timeadv present>",
"<timenoun>","<timenoun dayofweek>","<timenoun holiday>","<timenoun month>","<timenoun timeofday>","<timenoun unit>",
"<unit>","<unit energy>","<unit factor>","<unit large>","<unit potential>","<unit power>","<unit capacitance>","<unit current>","<unit small>","<unit length>","<unit volume>","<unit weight>",
"<verbimg>",
"<say>",
"<verb>","<verb intransitive>","<verb eat>","<verb transitive>","<verb pose>","<verb motion>","<verb insert>","<verb political>","<verb move>","<verb legal>","<verb liquid>","<verb violent>","<verb walk>",
"<vocal>",
"<preposition>",
"<yn>","<yn no>","<yn yes>",
];
