var availableTags=[
"<abstract>","<abstract concept>","<abstract subjective>","<abstract social>","<abstract linguistic>",
"<activity>","<activity game>","<activity sport>","<activity board>","<activity video>",
"<adj>","<adj appearance>","<adj nationality>","<adj emotion>","<adj weather>","<adj nsfw>",
"<adv>","<adv sexy>","<adv emotion>",
"<color>","<color primary>","<color secondary>",
"<conj>",
"<country>","<country asia>","<country middleeast>","<country mediterranean>","<country europe>","<country southamerica>","<country oceania>","<country northamerica>","<country africa>","<country centralamerica>","<country caribbean>","<country eurasia>",
"<emo>",
"<em>",
"<x>",
"<face>",
"<firstname>","<firstname male>","<firstname female>","<firstname neutral>",
"<greet>",
"<surname>",
"<noun>","<noun body>","<noun hole>","<noun person>","<noun sex>","<noun weapon>","<noun animal>","<noun tool>","<noun food>","<noun drug>","<noun article>","<noun fruit>","<noun container>","<noun furniture>","<noun instrument>","<noun plant>","<noun shape>","<noun ball>","<noun surface>","<noun liquid>","<noun long>","<noun dog>","<noun job>","<noun round>","<noun clothes>","<noun vehicle>","<noun insect>","<noun nsfw>",
"<sound>",
"<title>",
"<place>","<place building>","<place indoor>","<place natural>","<place outdoor>",
"<prefix>","<prefix position>","<prefix quantity>","<prefix scale>","<prefix anatomy>",
"<prepos>","<prepos space>","<prepos time>",
"<pron>","<pron male>","<pron female>","<pron neutral>",
"<quality>","<quality physical>","<quality human>",
"<rel>","<rel male>","<rel female>","<rel neutral>",
"<sconj>",
"<substance>","<substance liquid>","<substance nsfw>",
"<timeadv>","<timeadv time>","<timeadv past>","<timeadv present>","<timeadv frequency>",
"<timenoun>","<timenoun timeofday>","<timenoun dayofweek>","<timenoun month>","<timenoun holiday>","<timenoun unit>",
"<unit>","<unit length>","<unit small>","<unit factor>","<unit large>","<unit weight>","<unit volume>","<unit pressure>","<unit energy>","<unit potential>","<unit capacitance>","<unit current>","<unit power>","<unit inductance>",
"<verbimg>",
"<say>",
"<verb>","<verb emotion>","<verb transitive>","<verb walk>","<verb intransitive>","<verb sex>","<verb pose>","<verb eat>","<verb liquid>","<verb motion>","<verb insert>","<verb violent>","<verb political>","<verb legal>","<verb move>",
"<vocal>",
"<preposition>",
"<yn>","<yn yes>","<yn no>",
];
